name: homelab

networks:
  homelab-network:
    name: homelab-network-default
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  frontend-network:
    name: homelab-network-frontend
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
  backend-network:
    name: homelab-network-backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.20.0/24
  monitoring-network:
    name: homelab-network-monitoring
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.30.0/24

services:
  # --- DNS Server ---
  dns:
    image: jpillora/dnsmasq
    container_name: dns-${DNS_CONTAINER_NAME:-aistack}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Paris
    ports:
      - "5053:53/udp"
    volumes:
      - ./deployment/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      homelab-network:
        ipv4_address: 192.168.10.2
      frontend-network:
        ipv4_address: 172.16.10.2
      backend-network:
        ipv4_address: 172.16.20.2
      monitoring-network:
        ipv4_address: 172.16.30.2
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "traefik.docker.local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  traefik:
    image: "traefik:v3.3.5"
    container_name: traefik-${TRAEFIK_CONTAINER_NAME:-aistack}
    depends_on:
      - dns
    dns:
      - 192.168.10.2
    environment:
      - TZ=Europe/Paris
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --accesslog.fields.names.StartUTC=drop
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.local`)"
      - "traefik.http.routers.api.service=api@internal"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8080/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - frontend-network
      - backend-network
      - monitoring-network
      - homelab-network

  # --- Whoami Debugging Service ---
  whoami:
    image: traefik/whoami:${WHOAMI_DOCKER_TAG:-latest}
    container_name: whoami-${WHOAMI_CONTAINER_NAME:-aistack}
    restart: unless-stopped
    depends_on:
      - dns
    dns:
      - 192.168.10.2
    networks:
      - backend-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-http.entrypoints=web"
      - "traefik.http.routers.whoami-http.rule=Host(`whoami.docker.local`)"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami-http.service=whoami-service"
      - "traefik.docker.network=backend"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # --- Portainer --- 
  portainer:
    image: portainer/portainer-ce:${PORTAINER_DOCKER_TAG:-latest}
    container_name: portainer-${PORTAINER_CONTAINER_NAME:-aistack}
    restart: unless-stopped
    depends_on:
      - dns
    dns:
      - 192.168.10.2
    networks:
      - frontend-network
      - backend-network
      - monitoring-network
      - homelab-network
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./morphale/portainer/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.docker.local`)"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-http.service=portainer-service"
      - "traefik.docker.network=frontend"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:${NGINX_DOCKER_TAG:-latest}
    container_name: nginx-${NGINX_CONTAINER_NAME:-aistack}
    restart: unless-stopped
    depends_on:
      - dns
    dns:
      - 192.168.10.2
    networks:
      - frontend-network
      - backend-network
      - monitoring-network
      - homelab-network
    ports:
      - "8081:80"
    volumes:
      - "/home/hroland/developpements/homelab/home-lab-72200/deployment/nginx/conf.d:/etc/nginx/conf.d"
      # Add a health-check file for Nginx
      - ./nginx-health-check.conf:/etc/nginx/conf.d/health-check.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-http.entrypoints=web"
      - "traefik.http.routers.nginx-http.rule=Host(`nginx.docker.local`)"
      - "traefik.http.services.nginx-service.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-http.service=nginx-service"
      - "traefik.docker.network=frontend"
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:80/health-check"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  # --- Watchtower - Automatic Updates ---
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_DOCKER_TAG:-latest}
    container_name: watchtower-${WATCHTOWER_CONTAINER_NAME:-aistack}
    restart: unless-stopped
    depends_on:
      - dns
    dns:
      - 192.168.10.2
    networks:
      - backend-network
      - monitoring-network
      - homelab-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --interval 3600 --cleanup --include-stopped --include-volumes
    environment:
      - WATCHTOWER_DEBUG=true
    labels:
      - "traefik.enable=false"
    # healthcheck:
    #   test: ["CMD", "ps", "aux"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
